# Generated by Django 3.2.16 on 2023-06-28 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescripts', '0003_auto_20230620_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptor',
            old_name='components',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='prescriptorcomponent',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='prescriptorcomponent',
            name='prescriptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptor_component', to='prescripts.prescriptor'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Тег'),
        ),
        migrations.AddConstraint(
            model_name='prescriptor',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='unique_prescriptor'),
        ),
    ]
