# Generated by Django 3.2.16 on 2023-07-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescripts', '0006_auto_20230702_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=264, verbose_name='Ингредиент'),
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(fields=('name', 'unit'), name='unique_component'),
        ),
    ]
