# Generated by Django 3.2.16 on 2023-07-12 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescripts', '0007_auto_20230703_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrescriptorComponent',
            new_name='RecipeComponent',
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название рецепта')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='prescriptors/images/', verbose_name='Изображение рецепта')),
                ('text', models.TextField(verbose_name='Описание рецепта')),
                ('cooking_time', models.PositiveSmallIntegerField(verbose_name='Время приготовления рецепта')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptors', to=settings.AUTH_USER_MODEL, verbose_name='Автор публикации')),
                ('ingredients', models.ManyToManyField(through='prescripts.RecipeComponent', to='prescripts.Component', verbose_name='Ингредиенты')),
                ('tags', models.ManyToManyField(related_name='prescriptors', to='prescripts.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.AlterField(
            model_name='favorite',
            name='prescriptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='prescripts.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipecomponent',
            name='prescriptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptor_component', to='prescripts.recipe'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='prescriptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='prescripts.recipe', verbose_name='Рецепт'),
        ),
        migrations.DeleteModel(
            name='Prescriptor',
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='unique_prescriptor'),
        ),
    ]
