# Generated by Django 3.2.16 on 2023-07-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230630_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('US', 'Пользователь'), ('AD', 'Администратор')], default='US', max_length=20, verbose_name='Роль'),
        ),
    ]
